---
- name: StartUp OCP4-2 VMs
  hosts: all

  tasks:

  - name: virsh shutdown
    shell: /usr/bin/virsh start master0.ocp4-2.genup.com

  - name: virsh shutdown
    shell: /usr/bin/virsh start master1.ocp4-2.genup.com

  - name: virsh shutdown
    shell: /usr/bin/virsh start master2.ocp4-2.genup.com
