---
- name: StartUp OCP4-1 VMs
  hosts: all

  tasks:

  - name: virsh start
    shell: /usr/bin/virsh start master0.ocp4-1.genup.com

  - name: virsh start
    shell: /usr/bin/virsh start master1.ocp4-1.genup.com

  - name: virsh start
    shell: /usr/bin/virsh start master2.ocp4-1.genup.com
